active_tab = "issues"
page_size = 100
theme_preset = "default"

[branches]
columns = [
    "Default",
    "Name",
    "Protected",
]

[environments]
columns = [
    "Deployment Status",
    "Name",
    "State",
]

[issues]
columns = [
    "Due Date",
    "ID",
    "Labels",
    "Milestone",
    "State",
    "Title",
]
group_ascending = false
group_by_column = "Milestone"

[issues.column_filters]
State = ["opened"]

[jobs]
columns = [
    "ID",
    "Matrix",
    "Name",
    "Stage",
    "Status",
]

[milestones]
columns = [
    "Due Date",
    "ID",
    "Progress",
    "State",
    "Title",
]
group_by_column = "Due Date"

[milestones.column_filters]
State = ["active"]

[mrs]
columns = [
    "Action",
    "ID",
    "Labels",
    "State",
    "Status",
    "Title",
]

[mrs.column_filters]
State = ["opened"]

[pipelines]
columns = [
    "ID",
    "Ref",
    "Stages",
    "Status",
]

[releases]
columns = [
    "Date",
    "Release Name",
    "Tag",
]

[runners]
columns = [
    "Active",
    "Description",
    "ID",
    "Status",
]

[todos]
columns = [
    "ID",
    "Project",
    "State",
    "Title",
    "Type",
]
