bg = "#121214"
border = "#505058"
border_focused = "#31bf67"
header_fg = "#31bf67"
highlight_bg = "#2b2b39"
inactive_bg = "#313244"
text_normal = "#d8dee9"
text_muted = "#82828a"
checked_bg = "#1c2637"
green = "#31bf67"
green_bg = "#142d1c"
red = "#e04953"
red_bg = "#321419"
blue = "#3d8bff"
blue_bg = "#0f233c"
yellow = "#ebb432"
yellow_bg = "#2d230f"
purple = "#a87af3"
purple_bg = "#261937"
gutter_bg = "#16161a"
separator_fg = "#3c3c44"
selection_bg = "#1e3250"
diff_del_fg = "#dc8c8c"
diff_del_bg = "#37161c"
diff_del_prefix = "#ff6464"
diff_add_fg = "#8cdc8c"
diff_add_bg = "#16301c"
diff_add_prefix = "#50dc50"
draft_comment_bg = "#2d2d14"
comment_bg = "#141e2d"
label_pink = "#f08cb4"
label_orange = "#fa7850"
label_cyan = "#28c8c8"
label_lime = "#b4e628"
label_light_violet = "#dca0ff"
markdown_h1 = "#bb99ee"
markdown_h2 = "#61afef"
markdown_h3 = "#98c379"
markdown_bullet = "#bb99ee"
markdown_quote = "#7f848e"
markdown_code_fg = "#e06c75"
markdown_code_bg = "#282c34"
markdown_bold = "#dcdfe4"
