bg = "#282828"
border = "#928374"
border_focused = "#b8bb26"
header_fg = "#b8bb26"
highlight_bg = "#3c3836"
inactive_bg = "#32302f"
text_normal = "#ebdbb2"
text_muted = "#928374"
checked_bg = "#32302f"
green = "#b8bb26"
green_bg = "#323714"
red = "#cc241d"
red_bg = "#3c140f"
blue = "#83a598"
blue_bg = "#192828"
yellow = "#d69315"
yellow_bg = "#32280f"
purple = "#d3869b"
purple_bg = "#371e28"
