bg = "#282828"
border = "#928374"
border_focused = "#b8bb26"
header_fg = "#b8bb26"
highlight_bg = "#3c3836"
inactive_bg = "#32302f"
text_normal = "#ebdbb2"
text_muted = "#928374"
checked_bg = "#32302f"
green = "#b8bb26"
green_bg = "#323714"
red = "#cc241d"
red_bg = "#3c140f"
blue = "#83a598"
blue_bg = "#192828"
yellow = "#d69315"
yellow_bg = "#32280f"
purple = "#d3869b"
purple_bg = "#371e28"
gutter_bg = "#1d2021"
separator_fg = "#665c54"
selection_bg = "#2d3228"
diff_del_fg = "#fb4934"
diff_del_bg = "#3c140f"
diff_del_prefix = "#fe8019"
diff_add_fg = "#b8bb26"
diff_add_bg = "#323714"
diff_add_prefix = "#8ec07c"
draft_comment_bg = "#3a3218"
comment_bg = "#1e2828"
label_pink = "#d3869b"
label_orange = "#fe8019"
label_cyan = "#83a598"
label_lime = "#b8bb26"
label_light_violet = "#d3869b"
markdown_h1 = "#d3869b"
markdown_h2 = "#83a598"
markdown_h3 = "#b8bb26"
markdown_bullet = "#d3869b"
markdown_quote = "#928374"
markdown_code_fg = "#fb4934"
markdown_code_bg = "#32302f"
markdown_bold = "#ebdbb2"
