bg = "#2e3440"
border = "#4c566a"
border_focused = "#88c0d0"
header_fg = "#88c0d0"
highlight_bg = "#3b4252"
inactive_bg = "#434c5e"
text_normal = "#d8dee9"
text_muted = "#949cae"
checked_bg = "#3b4252"
green = "#a3be8c"
green_bg = "#283723"
red = "#bf616a"
red_bg = "#371e1e"
blue = "#88c0d0"
blue_bg = "#1e323c"
yellow = "#ebcb8b"
yellow_bg = "#322d1e"
purple = "#b48ead"
purple_bg = "#2d232d"
gutter_bg = "#272c36"
separator_fg = "#4c566a"
selection_bg = "#2b3544"
diff_del_fg = "#bf616a"
diff_del_bg = "#371e1e"
diff_del_prefix = "#d08770"
diff_add_fg = "#a3be8c"
diff_add_bg = "#283723"
diff_add_prefix = "#88c0d0"
draft_comment_bg = "#33301e"
comment_bg = "#1e2832"
label_pink = "#b48ead"
label_orange = "#d08770"
label_cyan = "#88c0d0"
label_lime = "#a3be8c"
label_light_violet = "#b48ead"
markdown_h1 = "#b48ead"
markdown_h2 = "#88c0d0"
markdown_h3 = "#a3be8c"
markdown_bullet = "#b48ead"
markdown_quote = "#4c566a"
markdown_code_fg = "#bf616a"
markdown_code_bg = "#3b4252"
markdown_bold = "#eceff4"
