bg = "#1a1b26"
border = "#565f89"
border_focused = "#7aa2f7"
header_fg = "#7aa2f7"
highlight_bg = "#2c2e42"
inactive_bg = "#313244"
text_normal = "#a9b1d6"
text_muted = "#5b638c"
checked_bg = "#212440"
green = "#9ece6a"
green_bg = "#23371e"
red = "#db4b5f"
red_bg = "#37191e"
blue = "#7aa2f7"
blue_bg = "#19233c"
yellow = "#e0af68"
yellow_bg = "#322814"
purple = "#bb9af7"
purple_bg = "#281e37"

[icons]
tab_issue = "󰏪"
tab_pr = "󰊢"
tab_pipeline = "󰎨"
tab_job = "󱙃"
tab_runner = "󰐂"
tab_release = "󰷖"
tab_todo = "󰅝"
tab_milestone = "󰴀"
tab_branch = "󰲆"
tab_environment = "󰆍"
tab_terminal = "󰁨"
status_success = "✓"
status_failed = "✘"
status_running = "⟳"
status_pending = "◉"
header_github = "󱘧"
header_gitlab = "󱘤"
label_navigation = "☰"
label_terminal = "󰁨"
label_fetching = "⏳"
label_searching = "🔍"
label_filtered = "🔍"
